# Question 1

In [92]:
import numpy as np
np.__version__

'1.20.1'

In [93]:
import pandas as pd
columns=['Make','Model','Year','Engine Fuel Type','Engine HP','Engine Cylinders','Tansmission Type','Driven_Wheels','Number of Doors','Market Category','Vehicle Size','Vehicle Style','highway MPG','city mpg','Popularity','M']
data_frame=pd.read_csv("data.csv",names= columns)

# Question 2

In [94]:
data_frame.count()

Make                11915
Model               11915
Year                11915
Engine Fuel Type    11912
Engine HP           11846
Engine Cylinders    11885
Tansmission Type    11915
Driven_Wheels       11915
Number of Doors     11909
Market Category      8173
Vehicle Size        11915
Vehicle Style       11915
highway MPG         11915
city mpg            11915
Popularity          11915
M                   11915
dtype: int64

In [95]:
data_frame = data_frame.drop(data_frame.index[[0]])

data_frame

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Tansmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,M
1,BMW,1 Series M,2011,premium unleaded (required),335,6,MANUAL,rear wheel drive,2,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
2,BMW,1 Series,2011,premium unleaded (required),300,6,MANUAL,rear wheel drive,2,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
3,BMW,1 Series,2011,premium unleaded (required),300,6,MANUAL,rear wheel drive,2,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
4,BMW,1 Series,2011,premium unleaded (required),230,6,MANUAL,rear wheel drive,2,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
5,BMW,1 Series,2011,premium unleaded (required),230,6,MANUAL,rear wheel drive,2,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11910,Acura,ZDX,2012,premium unleaded (required),300,6,AUTOMATIC,all wheel drive,4,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11911,Acura,ZDX,2012,premium unleaded (required),300,6,AUTOMATIC,all wheel drive,4,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11912,Acura,ZDX,2012,premium unleaded (required),300,6,AUTOMATIC,all wheel drive,4,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11913,Acura,ZDX,2013,premium unleaded (recommended),300,6,AUTOMATIC,all wheel drive,4,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11914,Lincoln,Zephyr,2006,regular unleaded,221,6,AUTOMATIC,front wheel drive,4,Luxury,Midsize,Sedan,26,17,61,28995

In [96]:
len(data_frame.index)

11914

# Question 3

In [97]:
df=data_frame.groupby('Make').count()
df = df.sort_values(by=['Model'], ascending=False)[:3]
df

,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Tansmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,M
Make,,,,,,,,,,,,,,,
Chevrolet,1123,1123,1123,1117,1121,1123,1123,1123,622,1123,1123,1123,1123,1123,1123
Ford,881,881,881,868,881,881,881,881,499,881,881,881,881,881,881
Volkswagen,809,809,809,809,805,809,809,809,585,809,809,809,809,809,809

# Question 4

In [98]:
rslt_df['Model'].unique()

array(['100', '200', '80', '90', 'A3', 'A4 allroad', 'A4', 'A5', 'A6',
       'A7', 'A8', 'allroad quattro', 'allroad', 'Cabriolet', 'Coupe',
       'Q3', 'Q5', 'Q7', 'R8', 'RS 4', 'RS 5', 'RS 6', 'RS 7', 'S3', 'S4',
       'S5', 'S6', 'S7', 'S8', 'SQ5', 'TT RS', 'TT', 'TTS', 'V8'],
      dtype=object)

In [99]:
df = pd.DataFrame(rslt_df['Model'].unique())
df

                  0
0               100
1               200
2                80
3                90
4                A3
5        A4 allroad
6                A4
7                A5
8                A6
9                A7
10               A8
11  allroad quattro
12          allroad
13        Cabriolet
14            Coupe
15               Q3
16               Q5
17               Q7
18               R8
19             RS 4
20             RS 5
21             RS 6
22             RS 7
23               S3
24               S4
25               S5
26               S6
27               S7
28               S8
29              SQ5
30            TT RS
31               TT
32              TTS
33               V8

In [100]:
df.count()

0    34
dtype: int64

# Question 5

In [101]:
data_frame.isnull().sum()>0

Make                False
Model               False
Year                False
Engine Fuel Type     True
Engine HP            True
Engine Cylinders     True
Tansmission Type    False
Driven_Wheels       False
Number of Doors      True
Market Category      True
Vehicle Size        False
Vehicle Style       False
highway MPG         False
city mpg            False
Popularity          False
M                   False
dtype: bool

# Question 6

In [102]:
data_frame['Engine Cylinders'].median()

6.0

In [103]:
data_frame['Engine Cylinders'].mode()

0    4
dtype: object

In [104]:
data_frame['Engine Cylinders'].fillna(data_frame['Engine Cylinders'].mode())

1        6
2        6
3        6
4        6
5        6
        ..
11910    6
11911    6
11912    6
11913    6
11914    6
Name: Engine Cylinders, Length: 11914, dtype: object

In [105]:
data_frame['Engine Cylinders'].median()

6.0

# Question 7

# Select all the "Lotus" cars from the dataset.

In [106]:
lotus=data_frame[(data_frame['Make']=="Lotus")]

In [107]:
lotus

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Tansmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,M
3913,Lotus,Elise,2009,premium unleaded (required),189,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Convertible,27,21,613,43995
3914,Lotus,Elise,2009,premium unleaded (required),218,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3915,Lotus,Elise,2009,premium unleaded (required),189,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3916,Lotus,Elise,2010,premium unleaded (required),189,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3917,Lotus,Elise,2010,premium unleaded (required),218,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3918,Lotus,Elise,2011,premium unleaded (required),189,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Convertible,27,21,613,51845
3919,Lotus,Elise,2011,premium unleaded (required),217,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3920,Lotus,Elise,2011,premium unleaded (required),217,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Convertible,26,20,613,57950
4217,Lotus,Esprit,2002,premium unleaded (required),350,8,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,21,14,613,89825
4218,Lotus,Esprit,2003,premium unleaded (required),350,8,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,21,14,613,90825
4219,Lotus,Esprit,2004,premium unleaded (required),350,8,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,21,14,613,93225
4258,Lotus,Evora 400,2017,premium unleaded (required),400,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4259,Lotus,Evora 400,2017,premium unleaded (required),400,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4260,Lotus,Evora,2011,premium unleaded (required),276,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,27,18,613,64000
4261,Lotus,Evora,2011,premium unleaded (required),276,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,18,613,65500
4262,Lotus,Evora,2013,premium unleaded (required),276,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,18,613,66800
4263,Lotus,Evora,2013,premium unleaded (required),345,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,17,613,77100
4264,Lotus,Evora,2013,premium unleaded (required),345,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,17,613,78600
4265,Lotus,Evora,2013,premium unleaded (required),276,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,18,613,68300
4266,Lotus,Evora,2014,premium unleaded (required),345,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,17,613,78750
4267,Lotus,Evora,2014,premium unleaded (required),276,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,18,613,68750
4268,Lotus,Evora,2014,premium unleaded (required),345,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,17,613,79980
4269,Lotus,Evora,2014,premium unleaded (required),276,6,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,18,613,69980
4293,Lotus,Exige,2009,premium unleaded (recommended),257,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,20,613,74995
4294,Lotus,Exige,2009,premium unleaded (recommended),240,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4295,Lotus,Exige,2010,premium unleaded (recommended),240,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4296,Lotus,Exige,2011,premium unleaded (recommended),240,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4297,Lotus,Exige,2011,premium unleaded (recommended),257,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,20,613,70750
4298,Lotus,Exige,2011,premium unleaded (recommended),257,4,MANUAL,rear wheel drive,2,"Exotic,High-Performance",Compact,Coupe,26,20,613,74950

# Select only columns "Engine HP", "Engine Cylinders".

In [108]:
cols = ['Engine HP', 'Engine Cylinders']
df_subset=lotus.loc[:,cols]

# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

In [109]:
df_duplicates=df_subset.drop_duplicates()

In [110]:
df_duplicates

     Engine HP Engine Cylinders
3913       189                4
3914       218                4
3919       217                4
4217       350                8
4258       400                6
4260       276                6
4263       345                6
4293       257                4
4294       240                4

# Get the underlying NumPy array. Let's call it X.

In [111]:
df_duplicates['Engine HP'] = df_duplicates['Engine HP'].astype('float32')
df_duplicates['Engine Cylinders'] = df_duplicates['Engine Cylinders'].astype('float32')

X = df_duplicates.values

<ipython-input-111-c8576cef175d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_duplicates['Engine HP'] = df_duplicates['Engine HP'].astype('float32')
<ipython-input-111-c8576cef175d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_duplicates['Engine Cylinders'] = df_duplicates['Engine Cylinders'].astype('float32')

In [112]:
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]], dtype=float32)

In [113]:
XT = X.T
XTX = XT.dot(X)

In [114]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]], dtype=float32)

In [115]:
IXTX = np.linalg.inv(XTrnasX)
print(np.linalg.inv(XTrnasX))

[[ 5.5308425e-05 -2.9431982e-03]
 [-2.9431982e-03  1.6058844e-01]]

In [116]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [117]:
IXTXXT=IXTX.dot(XT)
w = IXTXXT.dot(y)

In [118]:
w[0]

4.594950191676617